create table NEW_TABLE_NAME
(
    ID                NUMBER            CONSTRAINT NEW_TABLE_NAME_ID_NN NOT NULL ENABLE,
    PARENT            NUMBER            CONSTRAINT NEW_TABLE_NAME_PARENT_NN NOT NULL ENABLE,

    STATUS            VARCHAR2(6)       CONSTRAINT NEW_TABLE_NAME_STATUS_NN NOT NULL ENABLE,

    UPDATED_BY        VARCHAR2(255 BYTE)                 CONSTRAINT NEW_TABLE_NAME_UPDATED_BY_NN NOT NULL ENABLE,
    UPDATED_AT        TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT localtimestamp CONSTRAINT NEW_TABLE_NAME_UPDATED_AT_NN NOT NULL ENABLE,

    CONSTRAINT NEW_TABLE_NAME_PK PRIMARY KEY (ID) ENABLE VALIDATE,
    CONSTRAINT NEW_TABLE_NAME_PARENT_FK FOREIGN KEY (PARENT) REFERENCES  <<PARENT>> (ID) ON DELETE CASCADE ENABLE VALIDATE
);

CREATE INDEX NEW_TABLE_NAME_PARENT_IDX ON NEW_TABLE_NAME(PARENT);

COMMENT ON TABLE NEW_TABLE_NAME IS 'Table description';
COMMENT ON COLUMN NEW_TABLE_NAME.ID               IS 'Unique record identifier';
COMMENT ON COLUMN NEW_TABLE_NAME.PARENT           IS 'Reference to parent';

COMMENT ON COLUMN NEW_TABLE_NAME.STATUS           IS 'Status, code RECORD_STATUS';

COMMENT ON COLUMN NEW_TABLE_NAME.UPDATED_BY       IS 'Who updated the record last time';
COMMENT ON COLUMN NEW_TABLE_NAME.UPDATED_AT       IS 'When the record was updated last time';

